### ISSUE TITLE
get.symfony.com/cloud/configurator installs incompatible sendmail

### ISSUE THREAD

**Issue by finnef** [symfonycorp/cloud-templates#27]
https://github.com/symfonycorp/cloud-templates/blob/5cc67d9cf7929460ac2fa262fc1ef7b06d3aa029/15-symfony-flex-platformsh.yaml#L59

The https://get.symfony.com/cloud/configurator sctipt installs sendmail in $APP_DIR/.global/bin. For the Platform.sh php container this overrides /usr/sbin/sendmail. The downloaded sendmail does not work (missing DLL). The Platform.sh provided sendmail is never used. This makes croncape fail too (if it needs to send emails).

Solution: test for sendmail existence and don't install if present?

This should be an issue in the configurator script, but I can't find a public repo for that, so posting this here.

**Comment by fabpot** [comment]
This has just been fixed now. The problem will go away the next time you deploy (`symfony deploy`, not just a redeploy unfortunately).

**Comment by finnef** [comment]
Hmm, after a new push to my master branch and auto redeploy in PSH it is still failing. If I SSH into the master php container and run
```
croncape php-security-checker -v
/app/.global/bin/sendmail: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/.global/bin/sendmail)

```

I have now worked around this by adding `rm /app/.global/bin/sendmail` before the `symfony-build` step in my .platform.app.yaml

**Comment by fabpot** [comment]
@finnef Does it works for you now?

**Comment by finnef** [comment]
It works, thanks!
